# Generated by Django 2.1.7 on 2019-02-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tads_simulator', '0003_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'projects', 'verbose_name_plural': 'projects'},
        ),
    ]
