# Generated by Django 2.1.5 on 2019-02-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tads_simulator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publications',
        ),
    ]
