# Generated by Django 2.1.5 on 2019-02-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tads_simulator', '0002_delete_publications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('project_technology', models.CharField(max_length=150)),
                ('cumulative_profit', models.IntegerField()),
            ],
            options={
                'db_table': 'SAMPLE_PROJECTS',
            },
        ),
    ]
